name: Automated Test for Lowest Number Script

on: [push]

jobs:
  test-lowest-number:
    name: Run All Test Cases
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Test Case 1 - Ten Numbers
        run: |
          python3 find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
          diff test_data/test1_expected.txt test_data/test1_output.txt

      - name: Test Case 2 - Single Number
        run: |
          python3 find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
          diff test_data/test2_expected.txt test_data/test2_output.txt

      - name: Test Case 3 - Empty File
        run: |
          python3 find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
          diff test_data/test3_expected.txt test_data/test3_output.txt
